---
#MySQL Settings
mysql_root_password: "Benji132"
mysql_db: "wordpress"
mysql_user: "denibenji89"
mysql_password: "Password123"

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"